### ISSUE TITLE
Add to QuDynamic?

### ISSUE THREAD

**Issue by Roger-luo** [Roger-luo/AdiaComput.jl#1]
@amitjamadagni

I wrote a simple simulator for adiabatic quantum computation.And do not have any dependencies. But I'm not sure it would be a solver for QuDynamic or just become a new repo for quantum computation simulators.

as far as I know,Julia does not have any package about quantum computation simulator.What about a new repo for simulators in quantum computation?

**Comment by amitjamadagni** [comment]
@Roger-luo I am not sure if we could have it as a solver in QuDynamics, but definitely we could provide an interface for the solvers, so that the user can solve the particular problem using different solvers. As far as I get it the evolved state is currently using the Euler method solver, but this can be made more general by borrowing some machinery already setup in QuDynamics. Also the idea of QuArray looks nice to me, but that said I am yet to play around with the QuBase construct to see if we can really pass continuous bases. 
Regarding a separate package, could you please open a issue on [JuliaQuantum](https://github.com/JuliaQuantum/JuliaQuantum.github.io/issues) repo so that we could have more discussion on the structure and insight of the package !  Thanks !

**Comment by Roger-luo** [comment]
As the this feature will be included in the quantum computation framework for JuliaQuantum in the future. I'll close this issue.
